version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container_test
    restart: always
    environment:
      POSTGRES_USER: rob
      POSTGRES_PASSWORD: Ocore2025**
      POSTGRES_DB: OneCore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
