-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ocr_usu_info
(
    id bigserial NOT NULL,
    pri_nombre character varying COLLATE pg_catalog."default",
    seg_nombres character varying COLLATE pg_catalog."default",
    pri_apellido character varying COLLATE pg_catalog."default",
    seg_apellido character varying COLLATE pg_catalog."default",
    tipo_doc integer,
    num_doc integer,
    correo text COLLATE pg_catalog."default",
    id_usuario integer,
    id_rol integer NOT NULL DEFAULT 2,
    CONSTRAINT ocr_usu_info_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ocr_usu_pass
(
    id serial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    id_usuario integer,
    fecha_sistema timestamp with time zone DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP),
    estado boolean DEFAULT true,
    caduca boolean DEFAULT false,
    CONSTRAINT ocr_usu_pass_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ocr_usu_usuario
(
    id bigserial NOT NULL,
    nombre_usario character varying COLLATE pg_catalog."default",
    req_token boolean DEFAULT true,
    tipo_cuenta_id integer,
    estado boolean DEFAULT true,
    fecha_registro time without time zone DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP),
    CONSTRAINT ocr_usu_usuario_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ocr_usurio_session
(
    id serial NOT NULL,
    id_usuario integer NOT NULL,
    sha_key text COLLATE pg_catalog."default" NOT NULL,
    fecha_sistema time without time zone DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP),
    estado boolean DEFAULT true,
    CONSTRAINT ocr_usurio_session_pk PRIMARY KEY (id),
    CONSTRAINT ocr_usurio_session_unique UNIQUE (sha_key)
);

ALTER TABLE IF EXISTS public.ocr_usu_info
    ADD CONSTRAINT ocr_usu_info_ocr_usu_usuario_fk FOREIGN KEY (id_usuario)
    REFERENCES public.ocr_usu_usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ocr_usu_pass
    ADD CONSTRAINT ocr_usu_pass_ocr_usu_usuario_fk FOREIGN KEY (id_usuario)
    REFERENCES public.ocr_usu_usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ocr_usurio_session
    ADD CONSTRAINT ocr_usurio_session_ocr_usu_usuario_fk FOREIGN KEY (id_usuario)
    REFERENCES public.ocr_usu_usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;